### ISSUE TITLE
Trail surface type / trail rendering

### ISSUE THREAD

**Issue by versatilehuman** [smartchicago/trailsy#115]
Creating visual difference for unpaved vs. single track/primitive/natural surface:

**Unpaved**
- Change to dashed in panel
- Same on map

**Single Track / Primitive / Natural Surface**
- Same in panel
- Change to `stroke-dasharray="0,10"` on map

**Comment by versatilehuman** [comment]
Added class for single track in CSS, needs to be applied:

`.fpccUNPAVED,.fpccUnpaved,.fpccunpaved{border-bottom-style:dashed}
.fpccPrimitive,.fpccprimitive,.fpccPRIMITIVE,.fpccSingletrack,.fpccSINGLETRACK,.fpccsingletrack{border-bottom-style:dotted}`

**Comment by shua123** [comment]
Alright this is up on gh-pages. I've changed the classes a bit. I have also set it up so that the map colors/styles are pulling from the css file. 

Panel - trail color/style: https://github.com/smartchicago/trailsy/blob/0585d4fccd2ddc5e4ae08724b7949e209804421a/styles/css/newguts.css#L171

map -trail color/style:
https://github.com/smartchicago/trailsy/blob/0585d4fccd2ddc5e4ae08724b7949e209804421a/styles/css/newguts.css#L190

**Comment by versatilehuman** [comment]
Looks good.
