### ISSUE TITLE
Only some activity markers are not shown at certain zoom levels

### ISSUE THREAD

**Issue by smarziano** [smartchicago/trailsy#34]
There seems to be some inconsistency for when activity markers are displayed. I did a search for "Caldwell Woods" and one activity marker showed up (for Bicycle Docking Station) although there are other activities nearby:

<img width="1207" alt="screen shot 2016-02-16 at 10 46 26 pm" src="https://cloud.githubusercontent.com/assets/5550969/13100128/4602ae98-d4ff-11e5-858c-9dd67702fd01.png">

Zooming in one level displays the two nearby activity markers:

<img width="1205" alt="screen shot 2016-02-16 at 10 49 24 pm" src="https://cloud.githubusercontent.com/assets/5550969/13100166/97b1599c-d4ff-11e5-96c7-61f206846ed1.png">

Then if you zoom out one level, all of the other activities are displayed:
<img width="1207" alt="screen shot 2016-02-16 at 10 52 08 pm" src="https://cloud.githubusercontent.com/assets/5550969/13100198/eeaeb334-d4ff-11e5-92df-f4e1ddb2fb38.png">

**Comment by shua123** [comment]
Yes that is intentional, though an area for refinement. Activities for an Entrance show up on search/click. All activities also show up at a certain zoom level in.

**Comment by versatilehuman** [comment]
Playing with the zoom, here are my thoughts:

Entrances seem to get lost as soon as activities appear. Also, once more of the activities are included, this will get messy. What about this approach:

![image](https://cloud.githubusercontent.com/assets/7032169/13118187/a6c6e8e8-d568-11e5-811e-59d482b021d1.png)

Initial zoom (pictured): red dots
+1: trails & red dots
+2: trails + signs (instead of red dots)
+3: trails + signs + activities (including parking, trail access, etc.)

Hoping this will help introduce the sign icon as the entrance before users get distracted by activity icons.

**Comment by shua123** [comment]
These zoom levels are now implemented on index-select2_v1 and index-select2_v3.

**Comment by shua123** [comment]
Need to refine these based on CUTGroup Test results

**Comment by versatilehuman** [comment]
Addressed in #56
