### ISSUE TITLE
Add paved & unpaved activity icons to trail info panel

### ISSUE THREAD

**Issue by shua123** [smartchicago/trailsy#4]
Unpaved vs. paved icons for trails:
* Unpaved: hike, bike, equestrian, cross-country ski
* Paved: hike, bike, cross-country ski

**Comment by shua123** [comment]
There are some Trail System + Color that have multiple surface types. How would we handle these?

Example:
![image](https://cloud.githubusercontent.com/assets/1593537/12523417/5afef00a-c11c-11e5-9ebe-0e0d5ae2ac72.png)

**Comment by shua123** [comment]
There is also trail_type vs trail_surface

**Comment by glw** [comment]
Im guessing this is happening where you have a paved trail and a separate unpaved trail both with the same color markings but within the same trail system. So for your particular example, in the North Branch trail system you have an unpaved section marked as Blue near Chipilly and Somme Woods, but you also have a Paved blue section Near the The Chicago Botanic Garden.

**Comment by glw** [comment]
Both trail_type and trail_surface are newer fields which try to keep track of our trails in greater detail. And because they are newer fields, they are sometimes blank. 

trail_type tries to follow the FPCC recreational master plan by expanding our trails designation beyond paved/unpaved. I dont have the master plans break down in front of me, but I can get that to you, if you'd like. In many case for the short term I've left the generic paved/unpaved designation.

trail_surface is similar to the surface tag in OSM. It records the specific material that makes up the trail surface; grass, asphault, cement, limestone, etc.

**Comment by shua123** [comment]
New plan from Ryan:
>Unpaved: hike, bike, equestrian, cross-country ski
Paved: hike, bike, cross-country ski
Primitive: hike

**Comment by shua123** [comment]
Done for now
