### ISSUE TITLE
Inconsistency of trail information in location result details panel

### ISSUE THREAD

**Issue by smarziano** [smartchicago/trailsy#48]
During the CUTGroup test, one (A) tester chose "Ottawa Trail Woods - North" and had questions about the trail type she saw on the map. This information was not listed in the detail panel. On other results, they do appear which makes me think that it might have something to do with how the result type is being listed. I think all preserve location results should have information about the relevant trails listed. (Are there any preserve locations that do not have any trails?)

![image](https://cloud.githubusercontent.com/assets/5550969/13677992/072cedcc-e6b2-11e5-91b0-ca58b3d78faf.png)

**Comment by shua123** [comment]
I think in this case there is no trail associated with "Ottawa Trail Woods - North." I don't think you can physically get to that trail from this entrance.

**Comment by versatilehuman** [comment]
I think this is a situation where graying out non-related icons/trails would be helpful (issue #43).

We are only mapping officially maintained trails, so not every preserve will have associated trails on the map. In reality, almost every preserve has at least primitive trails in the preserve -- but because we don't maintain them we don't want to promote these as locations with trails/trail related activities.
