### ISSUE TITLE
Certain Activities/Amenities have 0 results

### ISSUE THREAD

**Issue by smarziano** [smartchicago/trailsy#49]
During our CUTGroup test, we saw that some activities and amenities had 0 results which is inaccurate. Two examples are "Golf" and "Public Bathroom." We know that there have to be locations with golf and public bathrooms. For example, near LaBagh Woods there is the Billy Caldwell golf course with an activity icon seen on the map. I have, however, not seen an example of a location with a restroom icon on the map. 

Is this a problem with data not being connected to location result? This issue might be relevant to issue #43.

**Comment by shua123** [comment]
@smarziano When you say 0 results I assume you are talking about a scenario where someone types/selects golf or public bathroom in the search?

In the case of golf, part of the problem is that Billy Caldwell Golf Course entrance "parent" so it was orphaned. (So, yes #43 )

>  I have, however, not seen an example of a location with a restroom icon on the map.
As it is set up right now there wouldn't be a restroom icon on the map because restrooms do not have separate locations from the parent entrance (at least as the data is right now).

One thing to think about is maybe distinguishing in the detail panel between icons that would show up on the map and ones that wouldn't?

**Comment by smarziano** [comment]
@shua123  Are we limited by the data so that we can't add all activities and amenities to the map?

**Comment by versatilehuman** [comment]
@smarziano @shua123 Not all the activities make sense on the map and that's why they are absent. For example, hiking, biking, x-country skiing take place on trails and not at a single point. 

For the CUT Group test, public restroom data wasn't in there and the golf courses were orphaned as Josh said.

I like potentially distinguishing between mapped and non-mapped icons in the panel, but I'd like to see how everything functions without the data hiccups first.

**Comment by smarziano** [comment]
@versatilehuman @shua123 with this knowledge, I think this is absolutely something we should revisit when the data is all there and working.

**Comment by versatilehuman** [comment]
"potentially distinguishing between mapped and non-mapped icons in the panel" covered by #56 & #29
