### ISSUE TITLE
Trail Access accuracy

### ISSUE THREAD

**Issue by versatilehuman** [smartchicago/trailsy#88]
Ideas to make sure we aren't assigning Trail Access to POIs that don't have it, or over-assigning trails to POIs:

- Only show Trail Access in panel for those POIs that have a Trail Access Activity point connected to them
- Recalculate Trail Access with a smaller radius (thoughts @glw?)

Other thoughts @shua123?

**Comment by shua123** [comment]
> Only show Trail Access in panel for those POIs that have a Trail Access Activity point connected to them

So, where the POI is connected to an activity that is a trailhead. activities.atype="trailhead" ? I think that makes a lot of sense if you want to encourage access to trails via official trailheads? I think there are around 115 POIs that have a trailhead activity point. Would there be cases where we don't have a trailhead activity point but there is trail access that you want to highlight?

> Recalculate Trail Access with a smaller radius

My guess is distance might vary a lot by area? One POI might have 5 trail segments within 2000 where another could have 2.

In the email example of Maple Lake-East, it shows access to I&M because in the poi_to_trails table there is one segment with a distance of 2927 (ft?) that is I&M. The rest of the segments are Palos.

The email example of Miami Woods, it shows access to Thorn Creek because the poi_to_trails table has a segment 3345 distance away that is Thorn Creek subsystem.

**Comment by shua123** [comment]
In addition to distance adjustments we could also limit how many trail geom segments we consider. 
(Trail Segments within X distance from POI sorted by distance).limit(Y)

**Comment by versatilehuman** [comment]
So would something like this work:

_Only show trail access if activities.atype="trailhead" and only show segments from the closest trail system?_

The result would include all segments in the trail system, ordered by proximity:

First segment
"with access to"
All other segments

Whenever we show trail access, there should be a trailhead (and we are fixing that in the data). I think it could be beneficial to show trail connections, but I think that's something we look at later.

We are also getting segments pulled in from other trails on POIs:
![image](https://cloud.githubusercontent.com/assets/7032169/16739600/9c231500-4760-11e6-9885-ae3660c91227.png)

**Comment by versatilehuman** [comment]
Closing --> covered by #100
